---
title: "Hello here"
date: 2018-10-17
---

title: Hello here
author: Who else?
email: me@myself.com
description: > # this means to ignore newlines until "baseurl:"
  Playing around with jekyll and gh-pages. 

# social links
twitter_username: lumie31
github_username:  lumie31

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
